title: "Mathematics with SageMath"
author: "CIIEC, BUAP"
date: "May 10th, 2024"
source_code: "https://github.com/lvillasen/Mathematics-SageMath"
description: "Web app to perform math visualizations and calculations on a webpage"